### ISSUE TITLE
[BEAM-9678] Introduction Kata | Go SDK Code Katas

### ISSUE THREAD

**Issue by damondouglas** [damondouglas/beam#1]
Hello @lostluck 

At [BEAM-9678-intro-kata-golang](https://github.com/damondouglas/beam/tree/BEAM-9678-intro-kata-golang) I made a first attempt at [BEAM-9678](https://issues.apache.org/jira/browse/BEAM-9678) patterned after [the Java Katas](https://github.com/apache/beam/tree/master/learning/katas/java/Introduction) but added a [how to setup](https://github.com/damondouglas/beam/blob/BEAM-9678-intro-kata-golang/learning/katas/go/Introduction/task1/task.md) and a [how to test](https://github.com/damondouglas/beam/blob/BEAM-9678-intro-kata-golang/learning/katas/go/Introduction/task3/task.md) katas.

**Comment by lostluck** [comment]
Ah, ok, I almost missed this since it's a Github Issue in your own personal fork of apache/beam, rather than a PR against trunk's master branch.  A PR would let me comment on the the code.
(eg. there's the "create PR" button in the branch comparison page).
https://github.com/apache/beam/compare/master...damondouglas:BEAM-9678-intro-kata-golang

Conventionally, the Beam project receives PRs from users, rather than makes them on their behalf, which lets the discussion happen in the main repo, rather than off in the forks, where context could be lost.  

However, I understand if you want more feedback separately rather than committing to master in an incremental fashion.

---------

That said, some initial commentary: Overall, I like it!

Add the Apache 2.0 license header to all the files that can accept it without breaking function, there's a license check step. If the Java or Python equivalent don't have the licenses, then this is probably fine, but I'd be surprised if none of them do. This most likely effects the task*.go files. Be sure to have an empty line between the license and the package description/ package line to avoid the license becoming part of the package documentation.

Branding wise, the full name of the SDK is the Apache Beam Go SDK, shortened to the Beam Go SDK, or the Go SDK in beam contexts. We don't typically use "Golang" to refer to the language or the language for the SDK, as the official name is the Go Programming Language.

I recommend that somewhere in the initial pre-amble that the katas will not teach you Go, and that they assume some familiarity with the language. Pointing folks to https://golang.org/doc/#learning as a resource is sufficient.

Certainly since Go 1.13, (and probably 1.12) the main go tool supports Go Modules, so there shouldn't be any need to reference the vgo prototype tool at this juncture. The current release is Go 1.14 and modules are recommended. Yes, the SDK doesn't use them at this time, something something versioning...
